#!/usr/bin/env expect

# Script for automatically uploading to RAM and booting u-boot on Artik 5.
# Board must be reset after starting the script for it to run.

set timeout 240
spawn tio /dev/ttyUSB0

# TODO: Check whether board is already in U-Boot

# Stop autoboot and wait for usable prompt
expect "Hit any key to stop autoboot:"
send -- "\r"
expect "ARTIK5 #"

# Download the u-boot binary and start it
send -- "loady\r"
sleep .5
# Note that the line below does not contain a space, but ctrl-e encoded!
send -- "y"
expect "Enter file name:"
send -- "u-boot.bin\r"
expect "Done"
expect "ARTIK5 #"

# Jump to default load address
send -- "go 0x43E00000\r"

expect eof
